=== 2020.10
- GEを全て売る(得2.5～3倍)
- AT&Tをちょっと買う
　＝＞　四半期決算でちょっとプラスになる
=== 2020.11
==== 米株CFD
- 米石油株等、利益確定
- インテルを低位で持ち続けつつ、半導体セクターを追いかける
- AT&Tとベライゾンを持ち続け、5Gの
- ファイザーを追いかける
- 凡IT株イーベイを持ち続ける
- シスコ

==== 日本実株
【買った】
《配当株》エネオス　10月下旬に買い367円で買い、11月中旬で2～3%ほどプラス
    反省　350円で追って買えば良かった。チリの銅鉱にも注目
    目標株価を750円程度(2018年夏頃の水準)に据え、持ち続ける

《配当株》《親子》セブン銀行　コロナで減益したところ、236円で買う。226円で指値追い。
    米国、インドネシアのATM事業にも注目し、追いかける
    目標株価を600円程度(2015年夏頃の水準)に据え、持ち続ける

日本トムソン 342円のフェアバリューで購入。
    柱の直動案内機器は半導体、医療関連が堅調。設備投資低迷で工作機械向け減少。
    景気敏感株として、2018年夏1050円程度を参考に、700円以上での売却目指す。

【調べた後、買えたら買う】
日揮　EPCのDXに期待　800円台なら買いか
    目標株価を2600円程度(2018年春頃の水準)

《日産向け》ファルテック　自動運転対応ミリ波レーダーカバー
    すでに割安水準(配当4.9%)とのことだが、550円～530円で買い？
    
《売り予想》《親子》イソライト工業　セラミック～半導体製造装置　時価総額100億円程度
    自己資本比率70%強　成長は3年止まっている
        現在435円、330円くらいまで下がったら買いか



日経の柴犬

【ミニ株候補】
塩野義製薬
ソフトバンク　
《配当株？》日本カーボン　時価総額417億円

==== 出遅れ＆新興国の投信
以下を機械的に買い続ける
    三井中小　自動車寄り
    SBI中小 IT寄り
    J-REIT  リスクが減るまで上がらない
    新興国　アリババ、テンセント、台湾半導体、サムスンなど

うえ3つより顕著に下がった場合にたまに買う？
    eMaxim 8資産　※1/3 日本
    ニッセイ 4資産　※半分日本、半分債権　