== Catch the knife? That's a problem.　そのナイフ、掴むや掴まざるや。
=== 
次のテスラやテンセントを探して長期勝負するために

年に1回以内の相場下落は、CFD発注を手持ち金代わりにすることを兼ねて以下で対応する

== 年に1回以内の相場下落は、CFD発注を手持ち金代わりにすることを兼ねて以下で対応する
基本、「常に」２万円分のリスク対応をすることで、ほぼ通年、利益を出し続けられるはず

=== ほぼほぼ勝てるVIブルで弾幕を張る（１万円くらい）
過去の傾向からするとVIブルが2倍にあがる事象はまれ(1.5年に1回程度)
「常に」現在からVIブルが2倍になったときに稼げるように注文を入れておく
※　VIブル売り建てが、全滅するときは致し方なし、と割り切る

=== モーゲージ不動産etfとグローバル不動産etfでもそこそこ弾幕を張る（各５０００円くらい）
VIブルほど極端に値は下がらない
過去の顕著な価格低下例は、リーマンショックとコロナのみ
上がるときは結構上がるし、配当付くし良いはず
利率が下がりだしたら、少しずつ売って利益確定しておく。

=== 有事の金の乱高下に備える : 金ベアと金ブル（リスクを取り続ける）
割合とレバレッジの大きい金ベアを必死に売っておく。
補充的に金ブルの注文で金の値下げリスクに備える

=== 日経255CFDは限定的ながら、リスク対応となる（？）

== 年に1回もない波乱への対応　当座は円高・金高前提
なるべく逆張りはしない準備で乗り切る。
波乱時はCFD資産が半減するくらいは折り込んでおきたい。それを倍増させるように、これらの緊急対応で乗り切れるようにする

=== モーゲージ不動産etfとグローバル不動産etfで機動的に対応する
=> ほんとにやばそうなときに、不動産系etfに急低下対応した弾幕を張っていく（半値近くを想定）
（価格急降下になんとかついていき、配当で取り戻す）

=== ふるさと納税の先のべ(１０万円単位)
ふだんはふるさと納税をきちんとしておく
※　ふるさと納税を任意なので、やばいときは止める。

=== 価格下落時にマメに仮想通貨を買っておく（10～数十万円単位か）
金との連動性は必ずしも高くはない
買い建てももっておく
最終的な目標値は資産の1/5くらいか

=== 常に債権系の投資信託を一定額持っておく
債権系の投資信託を常に積み立てておく。（年利5%程度を目指して常に売り買いする）
インド債権を多めに持っておく。ハイイールド債は補助的に（よりリスクが高そう）※CFD全体の1/4くらいの金額があってよい気がする(eg. 25万円 : 100万円)

=== SBI証券、ig 証券 などで、コモディティに投資しておく
GLDM　金のetf

銅、銀、プラチナあたりをちまちまと売り買いする　最終的な目標値は資産の1/5くらいか

=== 数百万円投下するなら、ウイスキー投資はありかも。
ほんとにお金が余はじめたら、銘柄調べをする

=== 数千万円が使えるならば、国内不動産はリスク回避となる
キャンペーン