== S&P500もNQ100も上下動のリスクを増していると認識
    一方で、ドル安＆インフレ傾向で実物を持つメリットは小さい
    NISA投信でのS&P500と新興国株は下がった時に買うに戦略変更
    NISA投信での値上がり期待は、世界株式に当面集約
== NQ100は上下動を繰り返しながら、新たなグロース株が出てくることで長期的には上がっていくと予想
    今後数年は、TQQQのオートトライETFで上下動から利益を得ることにトライ
    毎月5万円程度を投入
        （当面は資金の半分程度を投入）＃親に電力株を売らせて、買わせたい
    TQQQが大きく下げた時に、（半導体セクター中心に）グロース個別株に実験的にトライする
    バンガード新興国株（VWO）も上下動するという意味では同様

== QQQ/VWO下落時のリスクヘッジ
=== 時々のテーマでFXを
カナダドル/円・買いとユーロ/円・売りの組み合わせは、どちらもスワップがプラスという点においても絶好の組み合わせ
    ただし、カナダドル/円とユーロ/円のどちらかは含み損を抱えている状態が続くので、最後は損切りしないと運用を終えられない

=== 金ベア、銀売り、銅ETF＆VIブル
    冬から春まで金ベアを少しずつ買い、秋口の金価格上昇に備える（数万円は持っていたい）
    金に対し銅が下がり始めたら、指数系ETFや利息CFDの利益確定を進め、銅ETFを少し買い、VIベア買いとVIブル売りの「待ち」を増やす
        仮想通貨も景気連動の側面が大きそうなので買っておく。
=== GMO NISA投信内のリスクヘッジ
    円高時に多少債権も買っておく（銅が下がったら債権を売って現金化し、日本株の下落待ちにする）
    シーズナリティで金も買っておく　数万円をCFDに回せるように
    日本のバリュー株も安値で少しずつ買っておく
=== GMO CFD（100万円を目指し少しずつ増やしていく）
==== VIベア&ブルを株価下落のシグナルとする
    VIベア&ブルを数万円は持っていく
    基本、個別株の値下がりでなく、市場全体のバリュー株の値下がり局面での買いにCFDを利用
    米バリュー株、株価指数、REIT　価格下落時にCFDで少しずつ買い足し、配当を得る戦略
    
=== 松井証券
    日本中小型株投信を少しずつ買っておく。10万円程度？
    円高時にインド債&ハイイールド債も
    銅上場投資信託(1693)をどう買えるかも、質問
=== サクソバンク証券

    急がなくて良いが、下落時に日本のバリュー株CFDを買い始める