= 1.5Kまで持っていった時の目標ポートフォリオ
大暴落あっても、大底で60%は生き残ることができるポートフォリオを作り上げる
大暴落後は、コロナ(数か月)～リーマン(数年)で回復させること目指す
目安としては、200万円を10年て1億～2億円とする　※　大暴落2年、8年で100倍増
500万円くらいをユニオンバンクのドル建てで持っておきたい(esp. SPXL, SPYD, 貴金属)

== 70%は株&REIT、金、仮想通貨、債券が各10%　
給与収入あるため、現金同等物は数十万円で良い(安心感あるセゾン投信も現金同等物扱いで良いか)。
　※　2021年4月時点では、株80%強、債券10%程度、金3%、現金同等物5%，仮想通貨ほぼゼロ
途中で暴落あった時は、状況に応じ、金融レバ3倍オートetf, REM CFD,　メインストリートなどをMAX100万円くらい仕込んで取り戻す
== 暴落対策組450万円
=== 金
この段階ではレバレッジをかける
シーズナリティを利用し、年20%程度の利益は取っておく
=== 仮想通貨
金が下がるシーズンに積み立てるのが一案か
=== 債券
==== 国債レバレッジ込みのものども
TMF 数十万円まで買って良い
ウルトラバランス(ハイイールド&投資適格)
USA360,ウルトラバランス世界株式の10%程度
==== インド公社債
年8%リターン目指して、こまめに買い続ける
暴落時はすこしずつ売る
==== ソーシャル・レンディング
数万円余った時の選択肢

== 株750万円の内訳は、テック&グロース400万円　体　バリュー・シクリカル350万円
TQQQ : ダウの犬的 : SPXL&小型株 : 配当貴族 : VTI
 = 5 :    4      :     3      :    2     :  1

=== グロース組(i.e.テック成分多め)
==== TQQQ系、250万円(レバ1～15倍)
全滅リスクを負うのは半分程度 TQQQオートETFを仕込み、ひっこめるのは年2回程度
FANG+レバ　毎日積立て、2・5・8月頃に利益確定
※　ジュニアNISAでもある程度買う

===== 現物ミニ株(数十万円)
  crowdstrike,Docusign,Zoom, Unityあたりを高頻度トレード(売りあたりの平均利益率20%程度？)
 ちょっとだけ　バイオハイテク　crispr
===== CFD組　数か月勝負
暴落あれば、facebookを仕込む
===== テーマ別投信(NISA)
大した期待はせずに、10～15%程度値上がりしたときにちょこちょこ売る

=== SPXL&ラッセル2000&THEO　150万円 (レバ3～10倍)
SPXLを年に3～5回買って、なるべく売らずに持っておく
ラッセル2000オートETFは6月から減速させて、9月以降に再参入する
VIベアもここに含める　ベアは6月以降適宜買っていき、sell in May

THEOは1.5年～2年に一度程度売って、2,5,8月対策に充てる　(若干　債券&コモディティを含む)

=== バリュー|シクリカル(i.e.テック成分平均以下)
==== ダウ&ユーロ50&REITの犬的　200万円
数%下落

日本株　Jpower、SMBC等　高配当ものを安値で仕込む
10%下落
ユーロ
===== 日本株投信組　※円安対策
225 4.3倍は年に3～5回買い、1月程度で利益確定
円安時に買う　10～50万円の枠内で売買
===== CFD組　通信&ヘルスケア中心
ベライゾン、AT&T 少しずつ増やしていく
メルク、ファイザー　 少しずつ増やしていく
コカ・コーラ　買い時only
フォード、GE シクリカル

===== ミニ株組
AMGEN, J&J,abbvie, unitedhealth, WBA 株価指数暴落時の値下がり低いものと期待
エムスリー、武田、中外、テルモ、第一工薬、小野薬品、GNI ちょこちょこと売買(シクリカル扱い)
===== REIT　
米国 REITブル 3x 当面のインフレ―対策&バッファー面の主役　
JRE　円安安値時に買っておく
ユーロ、アジア　チョコチョコ積立を続ける

==== 配当貴族からSPYD ETF 100万円
年に数十回こまめに安値を拾えば、平均年リターン10%は超えられるか
大暴落時も70%は残ると期待

ユニオンバンクでSPYD ETF　S&P 500の構成銘柄のなかで、配当利回り上位80銘柄を集めたETF


==== 世界株式　50万円
NISA 積立　
10%程度下落時に現金代わりに売ってしまうため、比率は上がらない
VTI&USA360&世界株式

== 備忘録
== 2021年春の立ち位置
2月末からのNQ100下落を利用してグロース株の比率を高めた
== 2020年末の立ち位置
バリュー系米株CFDとREM（モーゲージ不動産CFD）が主力
    REM : iシェアーズ･モーゲージ不動産キャップドETF（iShares Mortgage Real Estate Capped ETF）のCFD
オートFXで少し稼いだ（ポンド・ユーロ）が、死んだ
ハイレバレッジ系投信などを知った

