= 1.5Kまで持っていった時の目標ポートフォリオ
== 70%は株&REIT、金、仮想通貨、債券が各10%　
給与収入あるため、現金同等物は数十万円で良い。
　※　2021年4月時点では、株80%強、債券10%程度、金3%、現金同等物5%，仮想通貨ほぼゼロ
== 株750万円の内訳は、テック&グロース8　体　バリュー・シクリカル7
TQQQ : ダウの犬的 : SPXL&小型株 : 配当貴族 : VTI
 = 5 :    4      :     3      :    2     :  1

=== グロース組(i.e.テック成分多め)
==== TQQQ系、250万円(レバ1～15倍)
全滅リスクを負うのは半分程度 TQQQオートETFを仕込み、ひっこめるのは年2回程度
FANG+レバ　毎日積立て、2・5・8月頃に利益確定
※　ジュニアNISAでもある程度買う

===== 現物ミニ株(数十万円)
  crowdstrike,Docusign,Zoom, Unityあたりを高頻度トレード(売りあたりの平均利益率20%程度？)
 ちょっとだけ　バイオハイテク　crispr
===== CFD組　数か月勝負
暴落あれば、facebookを仕込む
===== テーマ別投信(NISA)
大した期待はせずに、10～15%程度値上がりしたときにちょこちょこ売る

==== SPXL&ラッセル2000　150万円 (レバ3～10倍)
SPXLを年に3～5回買って、なるべく売らずに持っておく
ラッセル2000オートETFは6月から減速させて、9月以降に再参入する
VIベアもここに含める　ベアは6月以降適宜買っていき、sell in May

=== バリュー|シクリカル(i.e.テック成分平均以下)
==== ダウ&ユーロ50&REITの犬的　200万円
数%下落

日本株　Jpower、SMBC等　高配当ものを安値で仕込む
10%下落
ユーロ

===== CFD組
===== ミニ株組
===== REIT　

==== 配当貴族 100万円
年に数十回こまめに安値を拾えば、平均年リターン10%は超えられるか
大暴落時も70%は残ると期待

==== 世界株式　50万円
NISA 積立　
10%程度下落時に現金代わりに売ってしまうため、比率は上がらない
VTI&USA360&世界株式




== 備忘録
== 2021年春の立ち位置
2月末からのNQ100下落を利用してグロース株の比率を高めた
== 2020年末の立ち位置
バリュー系米株CFDとREM（モーゲージ不動産CFD）が主力
    REM : iシェアーズ･モーゲージ不動産キャップドETF（iShares Mortgage Real Estate Capped ETF）のCFD
オートFXで少し稼いだ（ポンド・ユーロ）が、死んだ
ハイレバレッジ系投信などを知った

